export const _products = [
  {
    id: 1,
    name: "Kapüşonlu Uzun Kollu Baskılı Kalın Erkek Sweatshirt",
    price: 119.99,
    img: "hoodie-red.png",
    colors: ["red"],
    isFavorite: false,
  },
  {
    id: 2,
    name: "LCW BASIC Kapüşonlu Uzun Kollu Fermuarlı Erkek Sweatshirt",
    price: 109.99,
    img: "sweatshirt-black-zip.png",
    colors: ["black", "white"],
    isFavorite: false,
  },
  {
    id: 3,
    name: "LCW BASIC Kapüşonlu Uzun Kollu Fermuarlı Erkek Sweatshirt",
    price: 119.99,
    img: "sweatshirt-gray-zip.png",
    colors: ["gray", "white"],
    isFavorite: false,
  },
  {
    id: 4,
    name: "LCW BASIC Bisiklet Yaka Uzun Kollu Kalın Erkek Sweatshirt",
    price: 89.99,
    img: "sweatshirt-khaki.png",
    colors: ["khaki"],
    isFavorite: false,
  },
  {
    id: 5,
    name: "LCW CASUAL Kapüşonlu Uzun Kollu Baskılı Erkek Sweatshirt",
    price: 119.99,
    img: "hoodie-black.png",
    colors: ["black", "white"],
    isFavorite: false,
  },
  {
    id: 6,
    name: "LCW CASUAL Kapüşonlu Uzun Kollu Baskılı Erkek Sweatshirt",
    price: 119.99,
    img: "hoodie-blue.png",
    colors: ["blue", "yellow"],
    isFavorite: false,
  },
  {
    id: 7,
    name: "LCW CASUAL Bisiklet Yaka Uzun Kollu Erkek Sweatshirt",
    price: 69.99,
    img: "sweatshirt-black.png",
    colors: ["black"],
    isFavorite: false,
  },
  {
    id: 8,
    name: "LCW CASUAL Kapüşonlu Fermuarlı Erkek Sweatshirt",
    price: 109.99,
    img: "sweatshirt-black-zip-2.png",
    colors: ["black"],
    isFavorite: false,
  },
  {
    id: 9,
    name: "Atatürk Baskılı Kapüşonlu Sweatshirt",
    price: 99.99,
    img: "sweatshirt-black-ataturk.png",
    colors: ["black", "white"],
    isFavorite: false,
  },
  {
    id: 10,
    name: "Kapüşonlu Uzun Kollu Baskılı Kalın Erkek Sweatshirt",
    price: 119.99,
    img: "sweatshirt-white-ataturk.png",
    colors: ["white", "black"],
    isFavorite: false,
  },
];
